product_importer/urls.py
import django_eventstream

from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from product_importer.core import views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # Product Importer urls
    path('index/', core_views.IndexView.as_view(), name='index'),
    path('products/', core_views.ProductListView.as_view(), name='product-list'),
    path('products/create/', core_views.ProductCreateView.as_view(),
         name='product-create'),
    path('products/<int:pk>/edit', core_views.ProductUpdateView.as_view(),
         name='product-update'),
    path('products/upload/', core_views.ProductUploadView.as_view(),
         name='product-upload'),
    path('event-hooks/', core_views.EventHookListView.as_view(),
         name='eventhook-list'),
    path('event-hooks/create/', core_views.EventHookCreateView.as_view(),
         name='eventhook-create'),
    path('event-hooks/<int:pk>/edit', core_views.EventHookUpdateView.as_view(),
         name='eventhook-update'),
    path('event-hooks/<int:pk>/edit', core_views.EventHookUpdateView.as_view(),
         name='eventhook-update'),

    path('import-events/', include(django_eventstream.urls),
         {'channels': ['product-import']}),

    path('uploads/sign-s3/', core_views.UploadsSignS3View.as_view(),
         name='uploads-sign-s3'),

    # Default all other urls to index view
    re_path(r'^.*', core_views.IndexView.as_view()),
]

product_importer/core/models.py
from django.db import models
from django.db.models.signals import post_save, pre_delete
from django.utils import timezone
from psqlextra.models import PostgresModel


class Product(PostgresModel):
    name = models.CharField(max_length=250)
    sku = models.SlugField(unique=True, max_length=150)
    description = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['id']


def product_uploads_directory_path(instance, filename):
    return f'product_data/{timezone.now().strftime("%Y/%m/%d")}/' \
           f'{timezone.now().timestamp()}.csv'


class ProductUpload(PostgresModel):
    """ Model for managing the upload of product data """
    STATUS_CHOICES = (
        ('S', 'Successful'),
        ('F', 'Failed'),
    )

    products_file = models.CharField(max_length=250)
    products_count = models.IntegerField(default=0)

    task_id = models.CharField(max_length=100, null=True, blank=True)
    started_at = models.DateTimeField(auto_now_add=True)
    ended_at = models.DateTimeField(null=True, blank=True)

    status = models.CharField(
        max_length=2, choices=STATUS_CHOICES, null=True, blank=True)
    is_active = models.BooleanField(default=True)


class EventHook(PostgresModel):
    """ Model for saving the web hooks for events """
    EVENT_CHOICES = (
        ('product.create', 'On Product Create'),
        ('product.update', 'On Product Update'),
    )

    event_type = models.CharField(max_length=100, choices=EVENT_CHOICES)
    endpoint = models.TextField()
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['id']


def async_trigger_event_hook(sender, instance, created, **kwargs):
    """ Call the function for triggering web hook calls"""
    from product_importer.core.tasks import trigger_event_hooks

    if created:
        event_type = 'product.create'
    else:
        event_type = 'product.update'
    trigger_event_hooks.delay(event_type, instance.id)


post_save.connect(async_trigger_event_hook, sender=Product)

product_importer/core/views.py
import boto3
import django_filters
from botocore.client import Config
from django.contrib.messages.views import SuccessMessageMixin
from django.conf import settings
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django_filters.views import FilterView
from rest_framework.generics import CreateAPIView
from rest_framework.generics import GenericAPIView
from rest_framework.response import Response

from product_importer.core.models import EventHook
from product_importer.core.models import Product
from product_importer.core.models import ProductUpload
from product_importer.core.serializers import ProductUploadSerializer


class IndexView(TemplateView):
    """ View for the default index page"""
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        """ Update the context for this page"""
        context = super().get_context_data(**kwargs)
        context['current_upload'] = ProductUpload.objects.\
            filter(is_active=True).first()
        context['last_upload'] = ProductUpload.objects.\
            filter(is_active=False).order_by('-started_at').first()
        return context


class ProductFilter(django_filters.FilterSet):
    query = django_filters.CharFilter(method='filter_by_query')
    active_only = django_filters.CharFilter(method='filter_by_active')

    @staticmethod
    def filter_by_query(queryset, name, value):
        return queryset.filter(
            Q(name__icontains=value) | Q(sku__icontains=value) |
            Q(description__icontains=value)
        )

    @staticmethod
    def filter_by_active(queryset, name, value):
        if value == 'on':
            return queryset.filter(is_active=True)
        return queryset

    class Meta:
        model = Product
        fields = ['is_active']


class ProductListView(FilterView):
    """ View for listing of products """
    template_name = 'product_list.html'
    model = Product
    filterset_class = ProductFilter
    paginate_by = 10


class ProductCreateView(SuccessMessageMixin, CreateView):
    """ View for creating a product """
    template_name = 'product_form.html'
    model = Product
    fields = ['sku', 'name', 'description', 'is_active']
    success_url = reverse_lazy('product-list')
    success_message = 'Product <strong>%(name)s</strong> has been ' \
                      'created successfully'


class ProductUpdateView(SuccessMessageMixin, UpdateView):
    """ View for updating a product """
    template_name = 'product_form.html'
    model = Product
    fields = ['sku', 'name', 'description', 'is_active']
    success_url = reverse_lazy('product-list')
    success_message = 'Product <strong>%(name)s</strong> has been ' \
                      'edited successfully'


class ProductUploadView(CreateAPIView):
    serializer_class = ProductUploadSerializer
    success_url = reverse_lazy('index')


class EventHookListView(ListView):
    """ View for listing of Event Hooks """
    template_name = 'eventhook_list.html'
    model = EventHook
    paginate_by = 10


class EventHookCreateView(SuccessMessageMixin, CreateView):
    """ View for creating an event hook """
    template_name = 'eventhook_form.html'
    model = EventHook
    fields = ['event_type', 'endpoint']
    success_url = reverse_lazy('eventhook-list')
    success_message = 'Event Hook has been created successfully'


class EventHookUpdateView(SuccessMessageMixin, UpdateView):
    """ View for updating an eventhooks """
    template_name = 'eventhook_form.html'
    model = EventHook
    fields = ['event_type', 'endpoint']
    success_url = reverse_lazy('eventhook-list')
    success_message = 'Event Hook has been edited successfully'


class UploadsSignS3View(GenericAPIView):
    """ View for signing of s3 upload requests from frontend """

    def get(self, request):
        s3 = boto3.client('s3', region_name='ap-south-1',
                          config=Config(signature_version='s3v4'))
        signed_post = s3.generate_presigned_post(
            Bucket=settings.AWS_STORAGE_BUCKET_NAME,
            Key='product_data/' + request.GET['file_name'],
            Fields={"acl": "public-read",
                    "Content-Type": request.GET['file_type']},
            Conditions=[
                {"acl": "public-read"},
                {"Content-Type": request.GET['file_type']}
            ],
            ExpiresIn=3600
        )
        return Response(
            {'data': signed_post,
             'url': f'https://{settings.AWS_STORAGE_BUCKET_NAME}.'
                    f's3.amazonaws.com/{request.GET["file_name"]}'
             }
        )

product_importer/core/templates/eventhook_form.html
{% extends 'layout.html' %}

{% block title %}Product Importer - Create/Update Event Hook{% endblock %}

{% block body_content %}

  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap
    align-items-center pt-3 pb-2 mb-3 border-bottom">
    {% if form.instance.id %}
      <h1 class="h2">Edit Event Hook {{ form.instance.id }}</h1>
    {% else %}
      <h1 class="h2">Add a new Event Hook</h1>
    {% endif %}

  </div>

  <div class="row">
    <div class="col-4">
      <form class="" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_event_type">Event Type</label>

          <select class="form-control {% if form.event_type.errors %}is-invalid{% endif %}"
                  id="id_event_type" name="event_type">
            {% for value, text in form.event_type.field.choices %}
              <option value="{{ value }}" {% if form.instance.event_type == value%}selected {% endif %}>
                {{ text }}</option>
            {% endfor %}
          </select>
          {% if form.event_type.errors %}
            <div class="invalid-feedback">{{ form.event_type.errors.0 }}</div>
          {% endif %}
          <small class="form-text text-muted">Event which triggers the webhook</small>
        </div>
        <div class="form-group is-invalid">
          <label for="id_endpoint">Endpoint</label>
          {% if form.endpoint.errors %}
            <input type="text" class="form-control is-invalid" id="id_endpoint" name="endpoint"
                 value="{{ form.instance.endpoint|default_if_none:''}}">
            <div class="invalid-feedback">{{ form.endpoint.errors.0 }}</div>
          {% else %}
            <input type="text" class="form-control" id="id_endpoint" name="endpoint"
                 value="{{ form.instance.endpoint|default_if_none:''}}">
          {% endif %}

        </div>
        <div class="form-group">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" id="id_is_active" name="is_active"
              {% if form.instance.is_active %} checked {% endif %}>
            <label class="form-check-label" for="id_is_active">
              Active
            </label>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>

      </form>
    </div>
{#    <div class="col-sm"></div>#}
{#    <div class="col-sm"></div>#}
  </div>
{% endblock %}

product_importer/core/templates/eventhook_list.html
{% extends 'layout.html' %}
{% load core_tags %}

{% block title %}Product Importer - Event Hooks{% endblock %}

{% block body_content %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap
    align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Event Hooks <small class="text-muted">Manage your event hooks here</small></h1>

    <div class="btn-toolbar mb-2 mb-md-0">
      <a role="button" class="btn btn-primary btn-sm" href="{% url 'eventhook-create' %}">
        <span data-feather="plus"></span> Add Event Hook</a>

    </div>
  </div>

  <div class="table-responsive mt-2">
    <table class="table table-striped table-sm">
      <thead>
        <th>Event Type</th>
        <th>Endpoint</th>
        <th>Active</th>
      </thead>
      <tbody>
        {% for eventhook in eventhook_list %}
          <tr>
            <td><a href="{% url 'eventhook-update' eventhook.id %}">{{ eventhook.event_type }}</a></td>
            <td>{{ eventhook.endpoint }}</td>
            <td>{{ eventhook.is_active }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <nav aria-label="Paginate Event Hooks" class="d-flex">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{% param_replace page=page_obj.previous_page_number%}">Previous</a></li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a></li>
      {% endif %}

      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.next_page_number%}">Next</a></li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a></li>
      {% endif %}
    </ul>
    <span class="mt-2 ml-2 text-info"> {{ page_obj.start_index }} to {{ page_obj.end_index }} of {{ page_obj.paginator.count }} Event Hooks</span>
  </nav>
{% endblock %}

product_importer/core/templates/index.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block title %}Product Importer - Dashboard{% endblock %}

{% block head_css %}
  <link href="{%  static "css/jquery.dm-uploader.min.css" %}" rel="stylesheet">

{% endblock %}

{% block body_content %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Dashboard <small class="text-muted"> Upload Products and Overview</small></h1>
    <div class="btn-toolbar mb-2 mb-md-0">
    </div>
  </div>

  <input type="hidden" id="id_current_upload" value="{{ current_upload.id }}">
  <form class="col-md-6  dm-uploader dm-form" id="drag-and-drop-zone"
        action="{% url 'product-upload' %}" method="post">
    <input type="hidden" name="products_file" id ="id_products_file">
    {% if last_upload %}
      <p class="text-right small text-info">
        <span data-feather="download"></span>
        Last Import Performed @ {{ last_upload.ended_at }}</p>
    {% endif %}
    <div class="form-row">
      <div class="col-md-12 col-sm-12">
        <div class="from-group mb-2">
          <label>Upload Product CSV</label>
          <input type="text" class="form-control" aria-describedby="fileHelp"
                 placeholder="No file uploaded..." readonly="readonly" />

          <div class="progress mb-2 d-none">
            <div class="progress-bar progress-bar-striped progress-bar-animated bg-primary"
              role="progressbar"
              style="width: 0%;"
              aria-valuenow="0" aria-valuemin="0" aria-valuemax="0">
              0%
            </div>
          </div>

        </div>
        <div class="form-group">
          <div role="button" class="btn btn-primary mr-2">
            <span class=""></span> Browse Files
            <input type="file" title='Click to add Files' />
          </div>
          <small class="status text-muted">Select a file or drag it over this area..</small>
        </div>
      </div>
    </div>
    <div class=" mt-3 invisible" id="import-logs-1">
      <p class="text-primary">Product Import Currently in Progress
      <span class="spinner-grow text-primary" role="status"></span></p>

      <div class="overflow-auto" style="height: 200px" id="import-logs-2">
        <ul class="list-unstyled ml-3"></ul>
      </div>

    </div>

  </form>

{% endblock %}

{% block body_js %}
  <script src="{% static "js/jquery.dm-uploader.js" %}"></script>
  <script src="{% static 'django_eventstream/eventsource.min.js' %}"></script>
  <script src="{% static 'django_eventstream/reconnecting-eventsource.js' %}"></script>
  <script src="{% static "js/dashboard.js" %}"></script>

{% endblock %}

product_importer/core/templates/layout.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Abhishek Ram">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{%  static "css/layout.css" %}" rel="stylesheet">

    {% block head_css %}
    {% endblock head_css %}
  </head>

  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Product Importer</a>
{#      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">#}
{#      <ul class="navbar-nav px-3">#}
{#      <li class="nav-item text-nowrap">#}
{#        <a class="nav-link" href="#">Sign out</a>#}
{#      </li>#}
{#      </ul>#}
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'product-list' %}">
                  <span data-feather="shopping-cart"></span>
                  Products
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'eventhook-list' %}">
                  <span data-feather="settings"></span>
                  Event Hooks
                </a>
              </li>
            </ul>

          </div>
        </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          {% block body_content %}

          {% endblock body_content %}
        </main>
      </div>
    </div>

      <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
      <script src="{% static "js/layout.js" %}"></script>

      {% block body_js %}
      {% endblock body_js %}
  </body>
</html>

product_importer/core/templates/product_form.html
{% extends 'layout.html' %}

{% block title %}Product Importer - Create/Update Product{% endblock %}

{% block body_content %}

  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap
    align-items-center pt-3 pb-2 mb-3 border-bottom">
    {% if form.instance.id %}
      <h1 class="h2">Edit product {{ form.instance.sku }}</h1>
    {% else %}
      <h1 class="h2">Add a new Product</h1>
    {% endif %}

  </div>

  <div class="row">
    <div class="col-sm">
      <form class="" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_sku">SKU</label>
          {% if form.sku.errors %}
            <input type="text" class="form-control is-invalid" id="id_sku" name="sku"
                 value="{{ form.instance.sku|default_if_none:''}}">
            <div class="invalid-feedback">{{ form.sku.errors.0 }}</div>
          {% else %}
            <input type="text" class="form-control" id="id_sku" name="sku"
                 value="{{ form.instance.sku|default_if_none:''}}">
          {% endif %}
          <small class="form-text text-muted">A Unique identifier for this product</small>
        </div>
        <div class="form-group is-invalid">
          <label for="id_name">Name</label>
          {% if form.name.errors %}
            <input type="text" class="form-control is-invalid" id="id_name" name="name"
                 value="{{ form.instance.name|default_if_none:''}}">
            <div class="invalid-feedback">{{ form.name.errors.0 }}</div>
          {% else %}
            <input type="text" class="form-control" id="id_name" name="name"
                 value="{{ form.instance.name|default_if_none:''}}">
          {% endif %}

        </div>
        <div class="form-group">
          <label for="id_description">Description</label>
          <textarea class="form-control" id="id_description" name="description"
                    rows="3">{{ form.instance.description|default_if_none:''}}</textarea>
        </div>
        <div class="form-group">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" id="id_is_active" name="is_active"
              {% if form.instance.is_active %} checked {% endif %}>
            <label class="form-check-label" for="id_is_active">
              Active
            </label>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>

      </form>
    </div>
    <div class="col-sm"></div>
    <div class="col-sm"></div>
  </div>
{% endblock %}

product_importer/core/templates/product_list.html
{% extends 'layout.html' %}
{% load core_tags %}

{% block title %}Product Importer - Products{% endblock %}

{% block body_content %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap
    align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Products <small class="text-muted">Manage your products here</small></h1>

    <div class="btn-toolbar mb-2 mb-md-0">
      <a role="button" class="btn btn-primary btn-sm" href="{% url 'product-create' %}">
        <span data-feather="plus"></span> Add Product</a>

    </div>
  </div>

  <form method="get" class="mb-2">
    <div class="form-row align-items-center">
      <div class="col-7">
        <label class="sr-only" for="id_query">Query</label>
        <input type="text" class="form-control mb-2" id="id_query"
               name="query" placeholder="Type your query here"
               value="{{ request.GET.query|default_if_none:'' }}">
      </div>
      <div class="col-auto">
        <div class="form-check mb-2">
          <input class="form-check-input" type="checkbox" id="id_active_only"
                 name="active_only" {% if request.GET.active_only == "on" %}
                 checked {% endif %}>
          <label class="form-check-label" for="id_active_only">
            Active Only
          </label>
        </div>
      </div>
      <div class="col">
        <button type="submit" class="btn btn-primary mb-2">Search</button>
      </div>
    </div>
  </form>

  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <th>SKU</th>
        <th>Name</th>
        <th>Description</th>
        <th>Active</th>
      </thead>
      <tbody>
        {% for product in product_list %}
          <tr>
            <td><a href="{% url 'product-update' product.id %}">{{ product.sku }}</a></td>
            <td>{{ product.name }}</td>
            <td>{{ product.description }}</td>
            <td>{{ product.is_active }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="clearfix">



  <nav aria-label="Paginate Products" class="d-flex">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{% param_replace page=page_obj.previous_page_number%}">Previous</a></li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a></li>
      {% endif %}

      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.next_page_number%}">Next</a></li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a></li>
      {% endif %}
    </ul>
  <span class="mt-2 ml-2 text-info"> {{ page_obj.start_index }} to {{ page_obj.end_index }} of {{ page_obj.paginator.count }} Products</span>
  </nav>

   </div>
{% endblock %}